#!/bin/bash

INTERVAL=10

ipset restore < /root/firewall/lists/bfd_black.ipset &> /dev/null
ipset restore < /usr/local/bfd/whitelist.ipset

echo "Running bfd every $INTERVAL seconds..."
while true
do
	#echo "["`date +"%m-%d-%y %T"`"] checking..."
	/usr/local/sbin/bfd -q
	sleep $INTERVAL
done
