#!/bin/bash

INSTALL_PATH="/usr/local/bfd"
INTERVAL=10

ipset restore < "$INSTALL_PATH/bfd_black.ipset" &> /dev/null
ipset restore < "$INSTALL_PATH/bfd_white.ipset" &> /dev/null

echo "Running bfd every $INTERVAL seconds..."
while true
do
	#echo "["`date +"%m-%d-%y %T"`"] checking..."
	/usr/local/sbin/bfd -q
	sleep $INTERVAL
done
